[package]
name = "rust_dungeon_crawler"
version = "0.1.0"
edition = "2021"
author = "Mihai Anca <mihai.anca13@gmail.com>"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = "~0.8.1"
legion = "=0.3.1"